language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm
  
matrix:
  allow_failures:
    - php: '5.5'
    - php: '5.6'
    - php: '7.0'
    - php: hhvm
  fast_finish: true
  
env:
  - COMPOSER_BIN_DIR="components/composer/bin/"
  
before_script:
  - composer install