language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

sudo: false

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction

script:
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
