<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'PHPUnit_Framework_TestCase' => $vendorDir . '/liteframe/liteframe-core/src/libraries/PHPUnitFill/TestCase.php',
);
