<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'eftec\\tests\\' => array($vendorDir . '/eftec/bladeone/tests'),
    'eftec\\bladeone\\' => array($vendorDir . '/eftec/bladeone/lib'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Models\\' => array($baseDir . '/app/Models'),
    'Middlewares\\' => array($baseDir . '/app/Middlewares'),
    'LiteOnion\\' => array($vendorDir . '/avonnadozie/liteonion/src'),
    'LiteFrame\\' => array($vendorDir . '/liteframe/liteframe-core/src/liteframe'),
    'GO\\' => array($vendorDir . '/peppeocchi/php-cron-scheduler/src/GO'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib/Doctrine/Common/Inflector'),
    'Cron\\' => array($vendorDir . '/mtdowling/cron-expression/src/Cron'),
    'Controllers\\' => array($baseDir . '/app/Controllers'),
    'Commands\\' => array($baseDir . '/app/Commands'),
);
