<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3415c2c4388dd0e1e5127b361bb44082
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '25072dd6e2470089de65ae7bf11d3109' => __DIR__ . '/..' . '/symfony/polyfill-php72/bootstrap.php',
        '667aeda72477189d0494fecd327c3641' => __DIR__ . '/..' . '/symfony/var-dumper/Resources/functions/dump.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Php72\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\VarDumper\\' => 28,
            'Symfony\\Component\\HttpFoundation\\' => 33,
        ),
        'L' => 
        array (
            'LiteOnion\\' => 10,
            'LiteFrame\\' => 10,
        ),
        'G' => 
        array (
            'GO\\' => 3,
        ),
        'C' => 
        array (
            'Cron\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php72',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\VarDumper\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-dumper',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'LiteOnion\\' => 
        array (
            0 => __DIR__ . '/..' . '/avonnadozie/liteonion/src',
        ),
        'LiteFrame\\' => 
        array (
            0 => __DIR__ . '/..' . '/liteframe/liteframe-core/src/liteframe',
        ),
        'GO\\' => 
        array (
            0 => __DIR__ . '/..' . '/peppeocchi/php-cron-scheduler/src/GO',
        ),
        'Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/mtdowling/cron-expression/src/Cron',
        ),
    );

    public static $classMap = array (
        'Commands\\Command' => __DIR__ . '/../../..' . '/app/Commands/Command.php',
        'Commands\\SampleCommand' => __DIR__ . '/../../..' . '/app/Commands/SampleCommand.php',
        'Controllers\\Controller' => __DIR__ . '/../../..' . '/app/Controllers/Controller.php',
        'Controllers\\SampleController' => __DIR__ . '/../../..' . '/app/Controllers/SampleController.php',
        'Middlewares\\Middleware' => __DIR__ . '/../../..' . '/app/Middlewares/Middleware.php',
        'Middlewares\\SampleMiddleware' => __DIR__ . '/../../..' . '/app/Middlewares/SampleMiddleware.php',
        'Middlewares\\ValidateCSRFToken' => __DIR__ . '/../../..' . '/app/Middlewares/ValidateCSRFToken.php',
        'Models\\Model' => __DIR__ . '/../../..' . '/app/Models/Model.php',
        'Models\\SampleModel' => __DIR__ . '/../../..' . '/app/Models/SampleModel.php',
        'PHPUnit_Framework_TestCase' => __DIR__ . '/..' . '/liteframe/liteframe-core/src/libraries/PHPUnitFill/TestCase.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3415c2c4388dd0e1e5127b361bb44082::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3415c2c4388dd0e1e5127b361bb44082::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3415c2c4388dd0e1e5127b361bb44082::$classMap;

        }, null, ClassLoader::class);
    }
}
