<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb15b588cae57108002a368d64d3b9d08
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\HttpFoundation\\' => 33,
        ),
        'M' => 
        array (
            'Models\\' => 7,
            'Middlewares\\' => 12,
        ),
        'L' => 
        array (
            'LiteOnion\\' => 10,
            'LiteFrame\\' => 10,
        ),
        'G' => 
        array (
            'GO\\' => 3,
        ),
        'D' => 
        array (
            'Doctrine\\Common\\Inflector\\' => 26,
        ),
        'C' => 
        array (
            'Cron\\' => 5,
            'Controllers\\' => 12,
            'Commands\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Models\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Models',
        ),
        'Middlewares\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Middlewares',
        ),
        'LiteOnion\\' => 
        array (
            0 => __DIR__ . '/..' . '/avonnadozie/liteonion/src',
        ),
        'LiteFrame\\' => 
        array (
            0 => __DIR__ . '/..' . '/liteframe/liteframe-core/src/liteframe',
        ),
        'GO\\' => 
        array (
            0 => __DIR__ . '/..' . '/peppeocchi/php-cron-scheduler/src/GO',
        ),
        'Doctrine\\Common\\Inflector\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/inflector/lib/Doctrine/Common/Inflector',
        ),
        'Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/mtdowling/cron-expression/src/Cron',
        ),
        'Controllers\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Controllers',
        ),
        'Commands\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/Commands',
        ),
    );

    public static $classMap = array (
        'PHPUnit_Framework_TestCase' => __DIR__ . '/..' . '/liteframe/liteframe-core/src/libraries/PHPUnitFill/TestCase.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb15b588cae57108002a368d64d3b9d08::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb15b588cae57108002a368d64d3b9d08::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb15b588cae57108002a368d64d3b9d08::$classMap;

        }, null, ClassLoader::class);
    }
}
