language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  
script:
  - phpunit  --coverage-text --coverage-clover=coverage.clover
